### ISSUE TITLE
How to generate privkey.pem?

### ISSUE THREAD

**Issue by dohvis** [puilp0502/python-webnoti#1]
How can I generate privkey.pem? There's no documentation..

**Comment by puilp0502** [comment]
In a REPL:
```python
>>> from webnoti.utils import get_private_key
>>> get_private_key('privkey.pem', b'password', generate=True)
```
This will generate private key named `privkey.pem` with password `password` in current working directory.

**Comment by dohvis** [comment]
I don't want to use the key with password
